---
name: Conociendo a los objetos
locale: es
type: learning
beta: false
teacher_info: ''
language: wollok
id_format: "%05d"
order:
- 1
- 22
- 23
- 35
- 25
- 31
- 32
- 27
- 34
- 28
- 33
- 19
private: false
